swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
description: '![xss" title="</p><svg onload=alert(1)>](x)'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
