swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<img src=x onerror=alert(1)>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
